# Generated by Django 2.2.6 on 2019-11-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_id', models.FloatField(unique=True)),
                ('answer', models.CharField(max_length=500)),
                ('question', models.CharField(max_length=500)),
                ('value', models.FloatField()),
                ('airdate', models.DateField()),
                ('created_date', models.CharField(max_length=500)),
                ('updated_date', models.CharField(max_length=500)),
                ('category', models.TextField()),
                ('cate_id', models.FloatField()),
                ('category_info', models.CharField(max_length=500)),
            ],
        ),
    ]
