# Generated by Django 2.2.6 on 2019-11-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='updated_date',
        ),
    ]
