# Generated by Django 2.2.6 on 2019-11-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20191102_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='clue_id',
            field=models.FloatField(),
        ),
    ]
